service: rxtracker

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  apiGateway:
    apiKeys:
      - api-key-for-person1
      - api-key-for-person2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          private: true
